### ISSUE TITLE
STAMP DOCUMENTS

### ISSUE THREAD

**Issue by alexalloza** [DocuWare/REST-Sample-TS#1]
Hi! 
Im trying to implement Stamps functions in my Node Js Rest Api and I found some problems with this. I achieve all steps before stamp the document but in the moment when my API go to do the stamp something fails.

Error: 
`
{
    "error": "StatusCodeError: 500 - {\"Message\":\"There is an error in XML document (1, 1).\",\"Exception\":\"InvalidOperationException: There is an error in XML document (1, 1).\",\"Uri\":\"http://docuware7/DocuWare/Platform/FileCabinets/{myFIleCabinetID}/Sections/68989-70627/StampBestPosition?page=0\",\"Method\":\"POST\",\"StatusCode\":500,\"Status\":\"Internal Server Error\",\"InternalCode\":0}"
}
`

In the follow link I get a 404 response...

http://docuware7/DocuWare/Platform/FileCabinets/{myFIleCabinetID}/Sections/68989-70627/StampBestPosition?page=0\

But in my document I have this link, but I can't do anything with it. So What I have to do?

Thanks in advance!

**Comment by DWDoP** [comment]
Hey Alex, 

do you send a "Stamp placement"-JSON in your body during the POST Request?
Feel free to give us some more insights in your issue by sending us an email: sdk@docuware.com.
Please provide the url, body and headers if you do so.

Best regards
Dominik

**Comment by alexalloza** [comment]
Okay! I did it
