### ISSUE TITLE
Host ID issue

### ISSUE THREAD

**Issue by sendrel-lambdas** [DocuWare/REST-Sample-TS#10]
so at index.html it says
```
const hostID = '7b5ed19b-bfd6-46e9-8a3b-efd2a4499666'; //has to be unique per machine
```
"has to be unique per machine"

So I have this container where it connects to docuware and etc.. which works. I tried changing the host id using https://www.guidgenerator.com/
and it doesn't work. It also hard to understand because `has to be unique per machine` and yet this docker container runs every 10 minutes? and also tried to run this locally and it works.

What exactly is this hostID?

I tried changing the hostID cause I need to run another docker container with different credentials (user, pass, org) and it seems like my problem is this "hostId" thing because it throws a 401 error and I have verified that the user and pass works. Also retrieve the org name through https://insertname.docuware.cloud/DocuWare/Platform/Organizations.

Please help. Thank you. Sorry for creating an issue.

**Comment by DWDoP** [comment]
Hey @sendrel-lambdas did you check if there are enough licenses left for the second logon? 

The purpose of the hostid is to summarize different services on the same host. If you run different services with the same user on a single machine, they only should use 1 license in case the same hostid is set.

**Comment by sendrel-lambdas** [comment]
Thanks. Now I know. Solved my problem. Closing this issue.
