### ISSUE TITLE
REST access with CORS from apps based on Angular or React

### ISSUE THREAD

**Issue by cgritton-bss** [DocuWare/REST-Sample-TS#61]
Is there a plan to setup a way to enable CORS support for applications developed in Angular or something similar for DocuWare cloud? If this is already possible what requirements are there? I have attempted to create a custom Angular app using typescript and Angulars httpClient module. 
I cannot get the logon to work as it responds with Access to XMLHttpRequest at 'https://<myorganizationsurl>.docuware.cloud/DocuWare/Platform/Account/Logon' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I have set headers 
Content-Type:  'application/x-www-form-urlencoded'
Accept: 'application/json'
I also configured options withCredentials: true

Thanks for any response to this as this would be an exciting opportunity for myself.

**Comment by DWDoP** [comment]
Hey Christopher,

in case your code is running as a service, it should not be an issue.
Only a browser cannot call the DocuWare REST directly due to the CORS restriction.
So far there is no possibilty to configure the CORS but I forwarded your request to the
responsible product department.

Best regards
Dominik

**Comment by cgritton-bss** [comment]
Thanks for the response. I have implemented my own .NET REST API backend and will work with the existing API to make calls to DocuWare server side. I look forward to this capability should it be available in the future though.
